#server:
#  port: 8895


#mybatis-plus:
#  mapper-locations: classpath*:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: false
#    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
