server:
  port: 8083

spring:
  profiles:
    active: common ,admin ,creator ,search ,blog ,manage

  devtools:
    restart:
      enabled: true

task:
  pool:
    corePoolSize: 20
    maxPoolSize: 40
    keepAliveSeconds: 300
    queueCapacity: 50
  cache-pool:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveSeconds: 300
    queueCapacity: 10

dataRender:
  IllegalWords: false

dev-pattern:
  devInfo: debug
  #devInfo: production
