server:
  port: 8083

spring:
  profiles:
    active: common ,service

  devtools:
    restart:
      enabled: true

task:
  pool:
    corePoolSize: 20
    maxPoolSize: 40
    keepAliveSeconds: 300
    queueCapacity: 50

dev-pattern:
  devInfo: debug
  #devInfo: production
