spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.55.121:3306/artsystem?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: GlassBottle*.

  redis:
    database: 0
    host: 118.31.55.121
    port: 6379
    password: Happy

  data:
    mongodb:
      host: 118.31.55.121
      port: 27017
      database: art-data
      username: admin3
      password: '142208'
      authentication-database: art-data
      #uri: mongodb://admin2:142208@118.31.55.121/art-data?authSource=art-data
      entity:
        base-package: com.art.artcommon.mongo

mybatis:
  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
