#server:
#  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.55.121:3306/artsystem?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: GlassBottle*.

#    redis:
#      database: 0
#      host: 118.31.55.121
#      port: 6379
#      password: Happy
#
#    rabbitmq:
#      host: 118.31.55.121
#      port: 5672
#      username: ems
#      password: 123
#      virtual-host: /

#mybatis:
#  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
#  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
