spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.55.121:3306/artsystem?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: GlassBottle*.
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000

  redis:
    database: 0
    host: 118.31.55.121
    port: 6379
    password: Happy
    lettuce:
      pool:
        max-active: 100
        max-idle: 8
        min-idle: 1
    timeout: PT10S #这里10秒查不到数据就超时

  data:
    mongodb:
      host: 118.31.55.121
      port: 27017
      database: art-data
      username: admin3
      password: '142208'
      authentication-database: art-data
      #uri: mongodb://admin2:142208@118.31.55.121/art-data?authSource=art-data
      entity:
        base-package: com.art.artcommon.mongo

  rabbitmq:
    host: 118.31.55.121
    port: 5672
    username: ems
    password: 123
    virtual-host: /
    connection-timeout: 60s

mybatis:
  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

send-email:
  data:
    hostName: smtp.qq.com
    charset: utf-8
    email: 1544096285@qq.com
    name: 系统用户服务
    userName: 1544096285@qq.com
    password: rxgauhezhrysihjj
    subject: 验证码，5分钟内有效

upload-file:
  data:
    port: 22
    password: HAPPY142208*.
    ip: 118.31.55.121
    user: root
    avatarpath: /usr/local/images/
  pool:
    max-total: 10
    max-idle: 10
    min-idle: 3

python:
  url: 127.0.0.1:9000
